version: "3.9"
services:
  gitea_backup_restore:
    container_name: gitea_backup_restore
    build:
      dockerfile: dockerfile.dev
      context: .
    volumes:
      - ./gitea_backup_restore:/home/gitea/gitea_backup_restore
      - ./gitea.config.dev:/data/gitea/conf/app.ini
      - ./data/gitea/git:/data/git
      - ./data/gitea/avatars:/data/gitea/avatars
      - ./data/gitea/repo-avatars:/data/gitea/repo-avatars
    environment:
      BACKUP_TARGET_FOLDER: "full_backup"
      BACKUP_METHODE: "s3"
      ENDPOINT_URL: "https://eu2.contabostorage.com"
      AWS_ACCESS_KEY_ID: "b84f8e7005244c8b94f36cb21a5f749a"
      AWS_SECRET_ACCESS_KEY: "7755a1228ca6b2ca484bdd69bb13d4a8"
      BACKUP_FILENAME: "gitea-backup-2023-02-23-19-23-59.zip"
      BACKUP_ENABLE: "True"
      BACKUP_MAX_RETENTION: 3
      BUCKET: gitea-backup
  gitea-db:
      image: mariadb:10.4.12
      container_name: gitea-db
      restart: always
      environment:
        - MYSQL_DATABASE=gitea
        - MYSQL_ROOT_PASSWORD=ASafePassWordToRulethemAll
        - MYSQL_USER=gitea
        - MYSQL_PASSWORD=ASafePassWordToRulethemAll
  gitea-app:
    image: gitea/gitea:1.24.5
    container_name: gitea-app
    restart: always
    environment:
      - RUN_CROND=true
      - VIRTUAL_PORT=3000
    ports:
    - '3000:3000'
    volumes:
      - ./gitea.config.dev:/data/gitea/conf/app.ini
      - ./data/gitea/git:/data/git
      - ./data/gitea/avatars:/data/gitea/avatars
      - ./data/gitea/repo-avatars:/data/gitea/repo-avatars
    depends_on:
      - gitea-db
