# E2E Testing: MySQL + FTP Configuration
# This file defines only the services needed for MySQL database with FTP storage testing

services:
  # MySQL database for Gitea
  gitea-db-mysql:
    image: mysql:8.0
    container_name: gitea-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: gitea123
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea123
    ports:
      - "3306:3306"
    volumes:
      - db-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pgitea123"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Gitea with MySQL
  gitea-mysql:
    image: gitea/gitea:1.21
    container_name: gitea-mysql
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db-mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea123
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__SECRET_KEY=e2e-test-secret-key-for-testing-only
      - GITEA__service__DISABLE_REGISTRATION=false
      - GITEA__service__REQUIRE_SIGNIN_VIEW=false
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"
    volumes:
      - gitea-data:/data
      - ./tests/e2e/gitea-config/app.mysql.ini:/data/gitea/conf/app.ini:ro
      - ./tests/e2e/gitea-config:/etc/gitea-config:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      gitea-db-mysql:
        condition: service_healthy

  # FTP server
  ftp:
    image: fauria/vsftpd
    container_name: vsftpd-e2e
    environment:
      FTP_USER: ftpuser
      FTP_PASS: ftppass123
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ftp-data:/home/vsftpd
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep :21 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Base backup/restore process
  gitea-backup-restore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitea-backup-e2e
    environment:
      # Backup configuration for FTP
      BACKUP_ENABLE: "true"
      BACKUP_METHODE: "ftp"
      FTP_HOST: "ftp"
      FTP_PORT: "21"
      FTP_USER: "ftpuser"
      FTP_PASSWORD: "ftppass123"
      FTP_PATH: "/backup"
      BACKUP_PREFIX: "e2e-test-ftp"
      BACKUP_MAX_RETENTION: "3"
      # Gitea configuration
      APP_INI_PATH: "/data/gitea/conf/app.ini"
    volumes:
      - gitea-data:/data
      - ./tests/e2e/gitea-config:/etc/gitea-config:ro
      - ./tests:/tests:ro
    command: ["sleep", "infinity"]
    depends_on:
      gitea-mysql:
        condition: service_healthy
      ftp:
        condition: service_healthy

volumes:
  ftp-data:
  db-mysql-data:
  gitea-data: