# E2E Testing: MySQL Configuration
# This file defines the MySQL database and Gitea with MySQL

services:
  # MySQL database for Gitea
  gitea-db-mysql:
    image: mysql:8.0
    container_name: gitea-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: gitea123
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea123
    ports:
      - "3306:3306"
    volumes:
      - db-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pgitea123"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Gitea with MySQL
  gitea-mysql:
    image: gitea/gitea:1.21
    container_name: gitea-mysql
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db-mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea123
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__SECRET_KEY=e2e-test-secret-key-for-testing-only
      - GITEA__service__DISABLE_REGISTRATION=false
      - GITEA__service__REQUIRE_SIGNIN_VIEW=false
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"
    volumes:
      - gitea-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      gitea-db-mysql:
        condition: service_healthy

volumes:
  db-mysql-data:
  gitea-data: