# E2E Testing: PostgreSQL + FTP Configuration
# This file defines only the services needed for PostgreSQL database with FTP storage testing

services:
  # PostgreSQL database for Gitea
  gitea-db-postgres:
    image: postgres:15
    container_name: gitea-db-postgres
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea123
    ports:
      - "5432:5432"
    volumes:
      - db-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitea -d gitea"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Gitea with PostgreSQL
  gitea-postgres:
    image: gitea/gitea:1.21
    container_name: gitea-postgres
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db-postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea123
      - GITEA__database__SSL_MODE=disable
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__SECRET_KEY=e2e-test-secret-key-for-testing-only
      - GITEA__service__DISABLE_REGISTRATION=false
      - GITEA__service__REQUIRE_SIGNIN_VIEW=false
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"
    volumes:
      - gitea-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      gitea-db-postgres:
        condition: service_healthy

volumes:
  db-postgres-data:
  gitea-data: